version: '3.8'

services:
  backend:
    image: cashtag:latest
    container_name: cashtag
    restart: always
    volumes:
      - /var/app/uploads/cashtag:/var/app/uploads/cashtag
    networks:
      - web
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/cashtagdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=BrieucGorin
    depends_on:
      - db
      
  frontend:
    image: cashvue:latest
    container_name: cashvue
    restart: always
    networks:
      - web
    depends_on:
      - backend

  db:
    image: mariadb:10.6
    container_name: cashtag_db
    networks:
      - web
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: BrieucGorin
      MARIADB_DATABASE: cashtagdb
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - /home/debian/var-lib-mysql/:/var/lib/mysql

networks:
  web:
    external: true