version: '3.8'

services:
  backend:
    image: cashtag:latest
    container_name: cashtag
    restart: always
    volumes:
      - /var/app/uploads/cashtag:/var/app/uploads/cashtag
    networks:
      - web
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/cashtagdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=BrieucGorin
      
  frontend:
    image: cashvue:latest
    container_name: cashvue
    restart: always
    networks:
      - web
    depends_on:
      - backend

networks:
  web:
    external: true