app:
  uploads:
    path: /var/app/uploads/cashtag

spring:
  datasource:
    url: jdbc:mariadb://cashtag_db:3306/dailymondb
    username: root
    password: BrieucGorin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 25
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml