spring:
  datasource:
    url: jdbc:mariadb://cashtag_db:3306/dailymondb
    username: root
    password: BrieucGorin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml